### ISSUE TITLE
Add Operating systems to the readme file

### ISSUE THREAD

**Issue by devcer** [devcer/devcer#2]
# TODO
- [x] Copy the icons from https://github.com/alexandresanlim/Badges4-README.md-Profile
- [x] Add them to the Readme file under `Operating systems` section

## Operating to add
- [x] Macos
- [x] Ubuntu
- [x] Windows
- [x] Android
- [x] iOS

**Comment by SubinDuresh** [comment]
Hi @devcer can you please assign this to me?
