### ISSUE TITLE
Add IDEs to the readme file

### ISSUE THREAD

**Issue by devcer** [devcer/devcer#3]
# TODO
- [x] Copy the icons from https://github.com/alexandresanlim/Badges4-README.md-Profile
- [x] Add them to the Readme file under `IDE's` section

## IDEs to add
- [x] VS Code
- [x] Codesandbox
- [x] Replit
- [x] JSFiddle
- [x] Sublime

**Comment by dissyulina** [comment]
Hi, I would like to add those. Please assign me, thanks.
