### ISSUE TITLE
Add testing frameworks to the readme file

### ISSUE THREAD

**Issue by devcer** [devcer/devcer#4]
# TODO
- [x] Copy the icons from https://github.com/alexandresanlim/Badges4-README.md-Profile
- [x] Add them to the Readme file under `Testing` section

## Items to add
- [x] Cypress
- [x] Jest
- [x] Jasmine

**Comment by dissyulina** [comment]
Hi @devcer , I'd like to work on this too if you don't mind.

**Comment by devcer** [comment]
@dissyulina thank you for your interest. However, I would like to leave this for other beginners to get started with Open source contributions. Hope you understand.

**Comment by dissyulina** [comment]
I understand @devcer , no problem!

**Comment by atharbeginner** [comment]
@devcer I would like to do this.
