### ISSUE TITLE
Add Tools to the readme file

### ISSUE THREAD

**Issue by devcer** [devcer/devcer#5]
# TODO
- [x] Copy the icons from https://github.com/alexandresanlim/Badges4-README.md-Profile
- [x] Add them to the Readme file under `Tools` section

## items to add
- [x] Firebase
- [x] Yarn
- [ ] NPM
- [ ] Webpack
- [ ] Gulp
- [ ] Sentry
- [ ] Jira
- [ ] Jenkins
- [ ] ESLint
- [ ] Prettier
- [ ] Sonarlint
- [ ] Storybook

**Comment by rosita-dmello** [comment]
Hi, I'd like to work on this!
