### ISSUE TITLE
Add Frameworks and libraries to the readme file

### ISSUE THREAD

**Issue by devcer** [devcer/devcer#7]
# TODO
- [ ] Copy the icons from https://github.com/alexandresanlim/Badges4-README.md-Profile
- [ ] Add them to the Readme file under `Frameworks and libraries` section

## Items to add
- [ ] React
- [ ] Redux
- [ ] NextJS
- [ ] Angular
- [ ] Angular JS
- [ ] Styled Components
- [ ] Tailwind css
- [ ] NodeJS
- [ ] Strapi
- [ ] Bootstrap
- [ ] ExpressJS
- [ ] Socket.io
- [ ] Leaflet
- [ ] Babel
- [ ] Underscore JS

**Comment by Tegridy** [comment]
@devcer 
Hi, could you assign it to me?
